;;;; package.lisp

(defpackage #:poem
  (:use #:common-lisp #:screamer #:snark)
  (:export
   #:$$abs
   #:$$bag
   #:$$bag*
   #:$$bag-to-list
   #:$$bag-union
   #:$$bagp
   #:$$ceiling
   #:$$complexp
   #:$$cons
   #:$$date-interval
   #:$$date-point
   #:$$difference
   #:$$empty-flat-bag
   #:$$empty-flat-list
   #:$$eq
   #:$$eqe
   #:$$flat-bag
   #:$$flat-list
   #:$$floor
   #:$$greater
   #:$$greatereq
   #:$$imagpart
   #:$$integerp
   #:$$less
   #:$$lesseq
   #:$$list
   #:$$list*
   #:$$list-to-bag
   #:$$list-to-string
   #:$$listp
   #:$$naturalp
   #:$$numberp
   #:$$product
   #:$$quote
   #:$$quotient
   #:$$quotient_c
   #:$$quotient_e
   #:$$quotient_f
   #:$$quotient_r
   #:$$quotient_t
   #:$$rationalp
   #:$$rcc8-c
   #:$$rcc8-dc
   #:$$rcc8-dr
   #:$$rcc8-ec
   #:$$rcc8-eq
   #:$$rcc8-not-ec
   #:$$rcc8-not-eq
   #:$$rcc8-not-ntpp
   #:$$rcc8-not-ntppi
   #:$$rcc8-not-p
   #:$$rcc8-not-pi
   #:$$rcc8-not-po
   #:$$rcc8-not-pp
   #:$$rcc8-not-ppi
   #:$$rcc8-not-tp
   #:$$rcc8-not-tpi
   #:$$rcc8-not-tpp
   #:$$rcc8-not-tppi
   #:$$rcc8-ntpp
   #:$$rcc8-ntppi
   #:$$rcc8-o
   #:$$rcc8-p
   #:$$rcc8-pi
   #:$$rcc8-po
   #:$$rcc8-pp
   #:$$rcc8-ppi
   #:$$rcc8-tp
   #:$$rcc8-tpi
   #:$$rcc8-tpp
   #:$$rcc8-tppi
   #:$$realp
   #:$$realpart
   #:$$reciprocal
   #:$$remainder_c
   #:$$remainder_e
   #:$$remainder_f
   #:$$remainder_r
   #:$$remainder_t
   #:$$round
   #:$$string-to-list
   #:$$stringp
   #:$$sum
   #:$$time-ii-after
   #:$$time-ii-before
   #:$$time-ii-contained-by
   #:$$time-ii-contains
   #:$$time-ii-disjoint
   #:$$time-ii-during
   #:$$time-ii-equal
   #:$$time-ii-finished-by
   #:$$time-ii-finishes
   #:$$time-ii-finishes-after
   #:$$time-ii-finishes-before
   #:$$time-ii-finishes-equal
   #:$$time-ii-intersects
   #:$$time-ii-meets
   #:$$time-ii-met-by
   #:$$time-ii-not-after
   #:$$time-ii-not-before
   #:$$time-ii-not-contains
   #:$$time-ii-not-during
   #:$$time-ii-not-equal
   #:$$time-ii-not-finished-by
   #:$$time-ii-not-finishes
   #:$$time-ii-not-finishes-after
   #:$$time-ii-not-finishes-before
   #:$$time-ii-not-finishes-equal
   #:$$time-ii-not-meets
   #:$$time-ii-not-met-by
   #:$$time-ii-not-overlapped-by
   #:$$time-ii-not-overlaps
   #:$$time-ii-not-started-by
   #:$$time-ii-not-starts
   #:$$time-ii-not-starts-after
   #:$$time-ii-not-starts-before
   #:$$time-ii-not-starts-equal
   #:$$time-ii-not-subsumed-by
   #:$$time-ii-not-subsumes
   #:$$time-ii-overlapped-by
   #:$$time-ii-overlaps
   #:$$time-ii-started-by
   #:$$time-ii-starts
   #:$$time-ii-starts-after
   #:$$time-ii-starts-before
   #:$$time-ii-starts-equal
   #:$$time-ii-subsumed-by
   #:$$time-ii-subsumes
   #:$$time-ip-after
   #:$$time-ip-before
   #:$$time-ip-contains
   #:$$time-ip-disjoint
   #:$$time-ip-finished-by
   #:$$time-ip-intersects
   #:$$time-ip-not-after
   #:$$time-ip-not-before
   #:$$time-ip-not-contains
   #:$$time-ip-not-finished-by
   #:$$time-ip-not-started-by
   #:$$time-ip-started-by
   #:$$time-pi-after
   #:$$time-pi-before
   #:$$time-pi-contained-by
   #:$$time-pi-disjoint
   #:$$time-pi-during
   #:$$time-pi-finishes
   #:$$time-pi-intersects
   #:$$time-pi-not-after
   #:$$time-pi-not-before
   #:$$time-pi-not-during
   #:$$time-pi-not-finishes
   #:$$time-pi-not-starts
   #:$$time-pi-starts
   #:$$time-pp-after
   #:$$time-pp-before
   #:$$time-pp-equal
   #:$$time-pp-not-after
   #:$$time-pp-not-before
   #:$$time-pp-not-equal
   #:$$truncate
   #:$$uminus
   #:$$utime-interval
   #:$$utime-point
   #:$false
   #:$i
   #:$int
   #:$o
   #:$rat
   #:$real
   #:$true
   #:$ttype
   #:&
   #:&allow-other-keys
   #:&aux
   #:&body
   #:&environment
   #:&key
   #:&optional
   #:&rest
   #:&whole
   #:*
   #:**
   #:***
   #:*break-on-signals*
   #:*compile-file-pathname*
   #:*compile-file-truename*
   #:*compile-me*
   #:*compile-print*
   #:*compile-verbose*
   #:*debug-io*
   #:*debugger-hook*
   #:*default-pathname-defaults*
   #:*dynamic-extent?*
   #:*error-output*
   #:*features*
   #:*gensym-counter*
   #:*hash-dollar-package*
   #:*hash-dollar-readtable*
   #:*iscream?*
   #:*load-pathname*
   #:*load-print*
   #:*load-truename*
   #:*load-verbose*
   #:*macroexpand-hook*
   #:*maximum-discretization-range*
   #:*minimum-shrink-ratio*
   #:*modules*
   #:*package*
   #:*print-array*
   #:*print-base*
   #:*print-case*
   #:*print-circle*
   #:*print-escape*
   #:*print-gensym*
   #:*print-length*
   #:*print-level*
   #:*print-lines*
   #:*print-miser-width*
   #:*print-pprint-dispatch*
   #:*print-pretty*
   #:*print-radix*
   #:*print-readably*
   #:*print-right-margin*
   #:*query-io*
   #:*random-state*
   #:*read-base*
   #:*read-default-float-format*
   #:*read-eval*
   #:*read-suppress*
   #:*readtable*
   #:*screamer-version*
   #:*standard-input*
   #:*standard-output*
   #:*strategy*
   #:*terminal-io*
   #:*tptp-environment-variable*
   #:*tptp-format*
   #:*tptp-input-directory*
   #:*tptp-input-directory-has-domain-subdirectories*
   #:*tptp-input-file-type*
   #:*tptp-output-directory*
   #:*tptp-output-directory-has-domain-subdirectories*
   #:*tptp-output-file-type*
   #:*trace-output*
   #:*v
   #:+
   #:++
   #:+++
   #:+v
   #:-
   #:--
   #:---
   #:-v
   #:/
   #://
   #:///
   #:/=
   #:/=v
   #:/v
   #:1+
   #:1-
   #:1-ary-functions>2-ary-functions-in-default-ordering
   #:1-ary-functions>2-ary-functions-in-default-ordering?
   #:<
   #:<=
   #:<=>
   #:<=v
   #:<v
   #:=
   #:=>
   #:=v
   #:>
   #:>=
   #:>=v
   #:>v
   #:?
   #:?u
   #:?v
   #:?w
   #:?x
   #:?y
   #:?z
   #:_
   #:~
   #:a-boolean
   #:a-booleanv
   #:a-member-of
   #:a-member-ofv
   #:a-numberv
   #:a-real-abovev
   #:a-real-belowv
   #:a-real-betweenv
   #:a-realv
   #:abort
   #:abs
   #:acons
   #:acos
   #:acosh
   #:add-method
   #:adjoin
   #:adjust-array
   #:adjustable-array-p
   #:agenda-length-before-simplification-limit
   #:agenda-length-before-simplification-limit?
   #:agenda-length-limit
   #:agenda-length-limit?
   #:agenda-ordering-function
   #:agenda-ordering-function?
   #:all-values
   #:allocate-instance
   #:allow-skolem-symbols-in-answers
   #:allow-skolem-symbols-in-answers?
   #:alpha-char-p
   #:alphanumericp
   #:an-integer
   #:an-integer-above
   #:an-integer-abovev
   #:an-integer-below
   #:an-integer-belowv
   #:an-integer-between
   #:an-integer-betweenv
   #:an-integerv
   #:and
   #:andv
   #:answer
   #:answer-if
   #:answers
   #:append
   #:apply
   #:apply-nondeterministic
   #:apply-substitution
   #:applyv
   #:apropos
   #:apropos-list
   #:aref
   #:arg1
   #:arg2
   #:args
   #:arithmetic-error
   #:arithmetic-error-operands
   #:arithmetic-error-operation
   #:array
   #:array-dimension
   #:array-dimension-limit
   #:array-dimensions
   #:array-displacement
   #:array-element-type
   #:array-has-fill-pointer-p
   #:array-in-bounds-p
   #:array-rank
   #:array-rank-limit
   #:array-row-major-index
   #:array-total-size
   #:array-total-size-limit
   #:arrayp
   #:ash
   #:asin
   #:asinh
   #:ask
   #:assert
   #:assert!
   #:assert-context
   #:assert-context?
   #:assert-rewrite
   #:assert-sequential
   #:assert-sequential?
   #:assert-supported
   #:assert-supported?
   #:assertion
   #:assertion-file-commands
   #:assertion-file-commands?
   #:assertion-file-format
   #:assertion-file-format?
   #:assertion-file-if-does-not-exist
   #:assertion-file-if-does-not-exist?
   #:assertion-file-keywords
   #:assertion-file-keywords?
   #:assertion-file-negate-conjectures
   #:assertion-file-negate-conjectures?
   #:assertion-file-package
   #:assertion-file-package?
   #:assertion-file-readtable
   #:assertion-file-readtable?
   #:assertion-file-verbose
   #:assertion-file-verbose?
   #:assoc
   #:assoc-if
   #:assoc-if-not
   #:assume
   #:assume-sequential
   #:assume-sequential?
   #:assume-supported
   #:assume-supported?
   #:assumption
   #:assumption
   #:atan
   #:atanh
   #:atom
   #:atom-with-keywords-inputter
   #:axiom
   #:bag
   #:bag-weight-factorial
   #:bag-weight-factorial?
   #:base-char
   #:base-string
   #:best-value
   #:bignum
   #:bit
   #:bit-and
   #:bit-andc1
   #:bit-andc2
   #:bit-eqv
   #:bit-ior
   #:bit-nand
   #:bit-nor
   #:bit-not
   #:bit-orc1
   #:bit-orc2
   #:bit-vector
   #:bit-vector-p
   #:bit-xor
   #:block
   #:boole
   #:boole-1
   #:boole-2
   #:boole-and
   #:boole-andc1
   #:boole-andc2
   #:boole-c1
   #:boole-c2
   #:boole-clr
   #:boole-eqv
   #:boole-ior
   #:boole-nand
   #:boole-nor
   #:boole-orc1
   #:boole-orc2
   #:boole-set
   #:boole-xor
   #:boolean
   #:booleanp
   #:booleanpv
   #:both-case-p
   #:bound?
   #:boundp
   #:break
   #:broadcast-stream
   #:broadcast-stream-streams
   #:built-in-class
   #:builtin-constant-weight
   #:builtin-constant-weight?
   #:butlast
   #:byte
   #:byte-position
   #:byte-size
   #:caaaar
   #:caaadr
   #:caaar
   #:caadar
   #:caaddr
   #:caadr
   #:caar
   #:cadaar
   #:cadadr
   #:cadar
   #:caddar
   #:cadddr
   #:caddr
   #:cadr
   #:call-arguments-limit
   #:call-method
   #:call-next-method
   #:can-be-constant-name
   #:can-be-free-variable-name
   #:car
   #:case
   #:catch
   #:ccase
   #:cdaaar
   #:cdaadr
   #:cdaar
   #:cdadar
   #:cdaddr
   #:cdadr
   #:cdar
   #:cddaar
   #:cddadr
   #:cddar
   #:cdddar
   #:cddddr
   #:cdddr
   #:cddr
   #:cdr
   #:ceiling
   #:cell-error
   #:cell-error-name
   #:cerror
   #:change-class
   #:changeable-properties-of-locked-constant
   #:changeable-properties-of-locked-constant?
   #:changeable-properties-of-locked-function
   #:changeable-properties-of-locked-function?
   #:char
   #:char-code
   #:char-code-limit
   #:char-downcase
   #:char-equal
   #:char-greaterp
   #:char-int
   #:char-lessp
   #:char-name
   #:char-not-equal
   #:char-not-greaterp
   #:char-not-lessp
   #:char-upcase
   #:char/=
   #:char<
   #:char<=
   #:char=
   #:char>
   #:char>=
   #:character
   #:characterp
   #:check-type
   #:checkpoint-theory
   #:cis
   #:class
   #:class-name
   #:class-of
   #:clear-input
   #:clear-output
   #:close
   #:closure
   #:clrhash
   #:cnf
   #:code-char
   #:coerce
   #:combine
   #:compilation-speed
   #:compile
   #:compile-file
   #:compile-file-pathname
   #:compiled-function
   #:compiled-function-p
   #:compiler-macro
   #:compiler-macro-function
   #:complement
   #:complex
   #:complexp
   #:compound-p
   #:compute-applicable-methods
   #:compute-restarts
   #:concatenate
   #:concatenated-stream
   #:concatenated-stream-streams
   #:cond
   #:condense
   #:condition
   #:conjecture
   #:conjecture
   #:conjugate
   #:cons
   #:consp
   #:constant-author
   #:constant-documentation
   #:constant-name
   #:constant-p
   #:constant-sort
   #:constant-source
   #:constantly
   #:constantp
   #:continue
   #:control-error
   #:copy-alist
   #:copy-list
   #:copy-pprint-dispatch
   #:copy-readtable
   #:copy-seq
   #:copy-structure
   #:copy-symbol
   #:copy-tree
   #:cos
   #:cosh
   #:count
   #:count-failures
   #:count-if
   #:count-if-not
   #:count-trues
   #:count-truesv
   #:ctypecase
   #:current-row-context
   #:debug
   #:decf
   #:decide
   #:declaim
   #:declaration
   #:declare
   #:declare-cancellation-law
   #:declare-constant
   #:declare-function
   #:declare-jepd-relations
   #:declare-operator-syntax
   #:declare-ordering-greaterp
   #:declare-proposition
   #:declare-rcc8-relations
   #:declare-relation
   #:declare-root-sort
   #:declare-root-sort?
   #:declare-snark-option
   #:declare-sort
   #:declare-sorts-incompatible
   #:declare-string-sort
   #:declare-string-sort?
   #:declare-subsort
   #:declare-time-relations
   #:declare-tptp-operators
   #:declare-tptp-sort
   #:declare-variable
   #:decode-float
   #:decode-universal-time
   #:default-1-ary-functions>2-ary-functions-in-default-ordering
   #:default-1-ary-functions>2-ary-functions-in-default-ordering?
   #:default-agenda-length-before-simplification-limit
   #:default-agenda-length-before-simplification-limit?
   #:default-agenda-length-limit
   #:default-agenda-length-limit?
   #:default-agenda-ordering-function
   #:default-agenda-ordering-function?
   #:default-allow-skolem-symbols-in-answers
   #:default-allow-skolem-symbols-in-answers?
   #:default-assert-context
   #:default-assert-context?
   #:default-assert-sequential
   #:default-assert-sequential?
   #:default-assert-supported
   #:default-assert-supported?
   #:default-assertion-file-commands
   #:default-assertion-file-commands?
   #:default-assertion-file-format
   #:default-assertion-file-format?
   #:default-assertion-file-if-does-not-exist
   #:default-assertion-file-if-does-not-exist?
   #:default-assertion-file-keywords
   #:default-assertion-file-keywords?
   #:default-assertion-file-negate-conjectures
   #:default-assertion-file-negate-conjectures?
   #:default-assertion-file-package
   #:default-assertion-file-package?
   #:default-assertion-file-readtable
   #:default-assertion-file-readtable?
   #:default-assertion-file-verbose
   #:default-assertion-file-verbose?
   #:default-assume-sequential
   #:default-assume-sequential?
   #:default-assume-supported
   #:default-assume-supported?
   #:default-bag-weight-factorial
   #:default-bag-weight-factorial?
   #:default-builtin-constant-weight
   #:default-builtin-constant-weight?
   #:default-changeable-properties-of-locked-constant
   #:default-changeable-properties-of-locked-constant?
   #:default-changeable-properties-of-locked-function
   #:default-changeable-properties-of-locked-function?
   #:default-declare-root-sort
   #:default-declare-root-sort?
   #:default-declare-string-sort
   #:default-declare-string-sort?
   #:default-eliminate-negations
   #:default-eliminate-negations?
   #:default-ex-join-negation
   #:default-ex-join-negation?
   #:default-feature-vector-symbol-number-folding
   #:default-feature-vector-symbol-number-folding?
   #:default-flatten-connectives
   #:default-flatten-connectives?
   #:default-input-floats-as-ratios
   #:default-input-floats-as-ratios?
   #:default-kbo-builtin-constant-weight
   #:default-kbo-builtin-constant-weight?
   #:default-kbo-status
   #:default-kbo-status?
   #:default-kbo-variable-weight
   #:default-kbo-variable-weight?
   #:default-level-pref-for-giving
   #:default-level-pref-for-giving?
   #:default-listen-for-commands
   #:default-listen-for-commands?
   #:default-meter-unify-bag
   #:default-meter-unify-bag?
   #:default-number-of-given-rows-limit
   #:default-number-of-given-rows-limit?
   #:default-number-of-rows-limit
   #:default-number-of-rows-limit?
   #:default-ordering-functions>constants
   #:default-ordering-functions>constants?
   #:default-partition-communication-table
   #:default-partition-communication-table?
   #:default-print-agenda-when-finished
   #:default-print-agenda-when-finished?
   #:default-print-assertion-analysis-notes
   #:default-print-assertion-analysis-notes?
   #:default-print-clocks-when-finished
   #:default-print-clocks-when-finished?
   #:default-print-final-rows
   #:default-print-final-rows?
   #:default-print-given-row-lines-printing
   #:default-print-given-row-lines-printing?
   #:default-print-given-row-lines-signalling
   #:default-print-given-row-lines-signalling?
   #:default-print-irrelevant-rows
   #:default-print-irrelevant-rows?
   #:default-print-options-when-starting
   #:default-print-options-when-starting?
   #:default-print-pure-rows
   #:default-print-pure-rows?
   #:default-print-rewrite-orientation
   #:default-print-rewrite-orientation?
   #:default-print-row-answers
   #:default-print-row-answers?
   #:default-print-row-constraints
   #:default-print-row-constraints?
   #:default-print-row-goals
   #:default-print-row-goals?
   #:default-print-row-length-limit
   #:default-print-row-length-limit?
   #:default-print-row-partitions
   #:default-print-row-partitions?
   #:default-print-row-reasons
   #:default-print-row-reasons?
   #:default-print-row-wffs-prettily
   #:default-print-row-wffs-prettily?
   #:default-print-rows-prettily
   #:default-print-rows-prettily?
   #:default-print-rows-shortened
   #:default-print-rows-shortened?
   #:default-print-rows-test
   #:default-print-rows-test?
   #:default-print-rows-when-derived
   #:default-print-rows-when-derived?
   #:default-print-rows-when-finished
   #:default-print-rows-when-finished?
   #:default-print-rows-when-given
   #:default-print-rows-when-given?
   #:default-print-rows-when-processed
   #:default-print-rows-when-processed?
   #:default-print-summary-when-finished
   #:default-print-summary-when-finished?
   #:default-print-symbol-table-warnings
   #:default-print-symbol-table-warnings?
   #:default-print-term-memory-when-finished
   #:default-print-term-memory-when-finished?
   #:default-print-time-used
   #:default-print-time-used?
   #:default-print-unorientable-rows
   #:default-print-unorientable-rows?
   #:default-prove-closure
   #:default-prove-closure?
   #:default-prove-sequential
   #:default-prove-sequential?
   #:default-prove-supported
   #:default-prove-supported?
   #:default-pruning-tests
   #:default-pruning-tests-before-simplification
   #:default-pruning-tests-before-simplification?
   #:default-pruning-tests?
   #:default-rcc8-region-sort-name
   #:default-rcc8-region-sort-name?
   #:default-refute-file-actions
   #:default-refute-file-actions?
   #:default-refute-file-closure
   #:default-refute-file-closure?
   #:default-refute-file-if-exists
   #:default-refute-file-if-exists?
   #:default-refute-file-ignore-errors
   #:default-refute-file-ignore-errors?
   #:default-refute-file-initialize
   #:default-refute-file-initialize?
   #:default-refute-file-options
   #:default-refute-file-options?
   #:default-refute-file-output-file
   #:default-refute-file-output-file?
   #:default-refute-file-verbose
   #:default-refute-file-verbose?
   #:default-rewrite-answers
   #:default-rewrite-answers?
   #:default-rewrite-constraints
   #:default-rewrite-constraints?
   #:default-row-argument-count-limit
   #:default-row-argument-count-limit?
   #:default-row-weight-before-simplification-limit
   #:default-row-weight-before-simplification-limit?
   #:default-row-weight-limit
   #:default-row-weight-limit?
   #:default-rpo-status
   #:default-rpo-status?
   #:default-run-time-limit
   #:default-run-time-limit?
   #:default-test-option14
   #:default-test-option14?
   #:default-test-option17
   #:default-test-option17?
   #:default-test-option18
   #:default-test-option18?
   #:default-test-option19
   #:default-test-option19?
   #:default-test-option2
   #:default-test-option20
   #:default-test-option20?
   #:default-test-option21
   #:default-test-option21?
   #:default-test-option23
   #:default-test-option23?
   #:default-test-option29
   #:default-test-option29?
   #:default-test-option2?
   #:default-test-option3
   #:default-test-option30
   #:default-test-option30?
   #:default-test-option36
   #:default-test-option36?
   #:default-test-option37
   #:default-test-option37?
   #:default-test-option38
   #:default-test-option38?
   #:default-test-option39
   #:default-test-option39?
   #:default-test-option3?
   #:default-test-option40
   #:default-test-option40?
   #:default-test-option41
   #:default-test-option41?
   #:default-test-option42
   #:default-test-option42?
   #:default-test-option43
   #:default-test-option43?
   #:default-test-option44
   #:default-test-option44?
   #:default-test-option45
   #:default-test-option45?
   #:default-test-option49
   #:default-test-option49?
   #:default-test-option50
   #:default-test-option50?
   #:default-test-option51
   #:default-test-option51?
   #:default-test-option52
   #:default-test-option52?
   #:default-test-option53
   #:default-test-option53?
   #:default-test-option54
   #:default-test-option54?
   #:default-test-option55
   #:default-test-option55?
   #:default-test-option56
   #:default-test-option56?
   #:default-test-option57
   #:default-test-option57?
   #:default-test-option58
   #:default-test-option58?
   #:default-test-option59
   #:default-test-option59?
   #:default-test-option6
   #:default-test-option60
   #:default-test-option60?
   #:default-test-option6?
   #:default-test-option8
   #:default-test-option8?
   #:default-test-option9
   #:default-test-option9?
   #:default-time-interval-sort-name
   #:default-time-interval-sort-name?
   #:default-time-point-sort-name
   #:default-time-point-sort-name?
   #:default-trace-dp-refute
   #:default-trace-dp-refute?
   #:default-trace-dpll-subsumption
   #:default-trace-dpll-subsumption?
   #:default-trace-optimize-sparse-vector-expression
   #:default-trace-optimize-sparse-vector-expression?
   #:default-trace-rewrite
   #:default-trace-rewrite?
   #:default-trace-unify
   #:default-trace-unify-bag-basis
   #:default-trace-unify-bag-basis?
   #:default-trace-unify-bag-bindings
   #:default-trace-unify-bag-bindings?
   #:default-trace-unify?
   #:default-unify-bag-basis-size-limit
   #:default-unify-bag-basis-size-limit?
   #:default-use-ac-connectives
   #:default-use-ac-connectives?
   #:default-use-answers-during-subsumption
   #:default-use-answers-during-subsumption?
   #:default-use-assertion-analysis
   #:default-use-assertion-analysis?
   #:default-use-associative-identity
   #:default-use-associative-identity?
   #:default-use-associative-unification
   #:default-use-associative-unification?
   #:default-use-clausification
   #:default-use-clausification?
   #:default-use-closure-when-satisfiable
   #:default-use-closure-when-satisfiable?
   #:default-use-condensing
   #:default-use-condensing?
   #:default-use-conditional-answer-creation
   #:default-use-conditional-answer-creation?
   #:default-use-constraint-purification
   #:default-use-constraint-purification?
   #:default-use-constraint-solver-in-subsumption
   #:default-use-constraint-solver-in-subsumption?
   #:default-use-constructive-answer-restriction
   #:default-use-constructive-answer-restriction?
   #:default-use-default-ordering
   #:default-use-default-ordering?
   #:default-use-dp-subsumption
   #:default-use-dp-subsumption?
   #:default-use-embedded-rewrites
   #:default-use-embedded-rewrites?
   #:default-use-equality-elimination
   #:default-use-equality-elimination?
   #:default-use-equality-factoring
   #:default-use-equality-factoring?
   #:default-use-extended-implications
   #:default-use-extended-implications?
   #:default-use-extended-quantifiers
   #:default-use-extended-quantifiers?
   #:default-use-factoring
   #:default-use-factoring?
   #:default-use-function-creation
   #:default-use-function-creation?
   #:default-use-hyperresolution
   #:default-use-hyperresolution?
   #:default-use-indefinite-answers
   #:default-use-indefinite-answers?
   #:default-use-input-restriction
   #:default-use-input-restriction?
   #:default-use-literal-ordering-with-hyperresolution
   #:default-use-literal-ordering-with-hyperresolution?
   #:default-use-literal-ordering-with-negative-hyperresolution
   #:default-use-literal-ordering-with-negative-hyperresolution?
   #:default-use-literal-ordering-with-paramodulation
   #:default-use-literal-ordering-with-paramodulation?
   #:default-use-literal-ordering-with-resolution
   #:default-use-literal-ordering-with-resolution?
   #:default-use-literal-ordering-with-ur-resolution
   #:default-use-literal-ordering-with-ur-resolution?
   #:default-use-lookahead-in-dpll-for-subsumption
   #:default-use-lookahead-in-dpll-for-subsumption?
   #:default-use-magic-transformation
   #:default-use-magic-transformation?
   #:default-use-negative-hyperresolution
   #:default-use-negative-hyperresolution?
   #:default-use-paramodulation
   #:default-use-paramodulation-only-from-units
   #:default-use-paramodulation-only-from-units?
   #:default-use-paramodulation-only-into-units
   #:default-use-paramodulation-only-into-units?
   #:default-use-paramodulation?
   #:default-use-partitions
   #:default-use-partitions?
   #:default-use-purity-test
   #:default-use-purity-test?
   #:default-use-quantifier-preservation
   #:default-use-quantifier-preservation?
   #:default-use-relevance-test
   #:default-use-relevance-test?
   #:default-use-replacement-resolution-with-x=x
   #:default-use-replacement-resolution-with-x=x?
   #:default-use-resolution
   #:default-use-resolution?
   #:default-use-resolve-code
   #:default-use-resolve-code?
   #:default-use-simplification-by-equalities
   #:default-use-simplification-by-equalities?
   #:default-use-simplification-by-units
   #:default-use-simplification-by-units?
   #:default-use-single-replacement-paramodulation
   #:default-use-single-replacement-paramodulation?
   #:default-use-sort-relativization
   #:default-use-sort-relativization?
   #:default-use-subsume-bag
   #:default-use-subsume-bag?
   #:default-use-subsumption
   #:default-use-subsumption-by-false
   #:default-use-subsumption-by-false?
   #:default-use-subsumption?
   #:default-use-term-memory-deletion
   #:default-use-term-memory-deletion?
   #:default-use-term-ordering
   #:default-use-term-ordering-cache
   #:default-use-term-ordering-cache?
   #:default-use-term-ordering?
   #:default-use-to-lisp-code
   #:default-use-to-lisp-code?
   #:default-use-unit-restriction
   #:default-use-unit-restriction?
   #:default-use-ur-pttp
   #:default-use-ur-pttp?
   #:default-use-ur-resolution
   #:default-use-ur-resolution?
   #:default-use-variable-name-sorts
   #:default-use-variable-name-sorts?
   #:default-use-well-sorting
   #:default-use-well-sorting?
   #:default-variable-sort-marker
   #:default-variable-sort-marker?
   #:default-variable-symbol-prefixes
   #:default-variable-symbol-prefixes?
   #:default-variable-to-lisp-code
   #:default-variable-to-lisp-code?
   #:default-variable-weight
   #:default-variable-weight?
   #:defclass
   #:defconstant
   #:defgeneric
   #:define-compiler-macro
   #:define-condition
   #:define-method-combination
   #:define-modify-macro
   #:define-screamer-package
   #:define-setf-expander
   #:define-symbol-macro
   #:defmacro
   #:defmethod
   #:defpackage
   #:defparameter
   #:defsetf
   #:defstruct
   #:deftype
   #:defun
   #:defvar
   #:delete
   #:delete-duplicates
   #:delete-file
   #:delete-if
   #:delete-if-not
   #:delete-package
   #:delete-row
   #:delete-row-context
   #:delete-rows
   #:denominator
   #:deposit-field
   #:dereference
   #:derivation-subsort-forms
   #:describe
   #:describe-object
   #:destructuring-bind
   #:digit-char
   #:digit-char-p
   #:directory
   #:directory-namestring
   #:disassemble
   #:divide-and-conquer-force
   #:division-by-zero
   #:do
   #:do*
   #:do-all-symbols
   #:do-external-symbols
   #:do-symbols
   #:do-tptp-problem
   #:do-tptp-problem0
   #:do-tptp-problem1
   #:documentation
   #:dolist
   #:domain-size
   #:dotimes
   #:double-float
   #:double-float-epsilon
   #:double-float-negative-epsilon
   #:dpb
   #:dribble
   #:dynamic-extent
   #:ecase
   #:echo-stream
   #:echo-stream-input-stream
   #:echo-stream-output-stream
   #:ed
   #:eighth
   #:either
   #:eliminate-negations
   #:eliminate-negations?
   #:elt
   #:embed
   #:encode-universal-time
   #:end-of-file
   #:endp
   #:enough-namestring
   #:ensure-directories-exist
   #:ensure-generic-function
   #:eq
   #:eql
   #:equal
   #:equal-p
   #:equalp
   #:equalv
   #:error
   #:etypecase
   #:eval
   #:eval-when
   #:evenp
   #:every
   #:ex-join-negation
   #:ex-join-negation?
   #:exp
   #:export
   #:expt
   #:extended-char
   #:factor
   #:fail
   #:fboundp
   #:fceiling
   #:fdefinition
   #:feature-vector-symbol-number-folding
   #:feature-vector-symbol-number-folding?
   #:ffloor
   #:fifo
   #:fifth
   #:file
   #:file-author
   #:file-error
   #:file-error-pathname
   #:file-length
   #:file-namestring
   #:file-position
   #:file-stream
   #:file-string-length
   #:file-write-date
   #:fill
   #:fill-pointer
   #:find
   #:find-all-symbols
   #:find-class
   #:find-if
   #:find-if-not
   #:find-method
   #:find-package
   #:find-restart
   #:find-symbol
   #:finish-output
   #:first
   #:fixnum
   #:flatten-connectives
   #:flatten-connectives?
   #:flet
   #:float
   #:float-digits
   #:float-precision
   #:float-radix
   #:float-sign
   #:floating-point-inexact
   #:floating-point-invalid-operation
   #:floating-point-overflow
   #:floating-point-underflow
   #:floatp
   #:floor
   #:fmakunbound
   #:fof
   #:for-effects
   #:force-output
   #:format
   #:formatter
   #:fourth
   #:fresh-line
   #:fround
   #:ftruncate
   #:ftype
   #:funcall
   #:funcall-nondeterministic
   #:funcallv
   #:function
   #:function-arity
   #:function-author
   #:function-documentation
   #:function-keywords
   #:function-lambda-expression
   #:function-logical-symbol-p
   #:function-name
   #:function-source
   #:function-symbol-p
   #:functionp
   #:gcd
   #:generic-function
   #:gensym
   #:gentemp
   #:get
   #:get-decoded-time
   #:get-dispatch-macro-character
   #:get-internal-real-time
   #:get-internal-run-time
   #:get-macro-character
   #:get-output-stream-string
   #:get-properties
   #:get-setf-expansion
   #:get-universal-time
   #:getf
   #:gethash
   #:give
   #:global
   #:go
   #:graphic-char-p
   #:ground?
   #:handler-bind
   #:handler-case
   #:has-author
   #:has-documentation
   #:has-name
   #:has-source
   #:hash-dollar-prin1
   #:hash-dollar-print
   #:hash-table
   #:hash-table-count
   #:hash-table-p
   #:hash-table-rehash-size
   #:hash-table-rehash-threshold
   #:hash-table-size
   #:hash-table-test
   #:head
   #:hint
   #:host-namestring
   #:hyperresolve
   #:hypothesis
   #:identity
   #:if
   #:ignorable
   #:ignore
   #:ignore-errors
   #:imagpart
   #:import
   #:in-kb
   #:in-language
   #:in-package
   #:in-row-context
   #:incf
   #:include
   #:initialize
   #:initialize-instance
   #:initialize-operator-syntax
   #:inline
   #:input-constant-symbol
   #:input-floats-as-ratios
   #:input-floats-as-ratios?
   #:input-function-symbol
   #:input-proposition-symbol
   #:input-relation-symbol
   #:input-stream-p
   #:input-term
   #:input-wff
   #:inspect
   #:integer
   #:integer-decode-float
   #:integer-length
   #:integerp
   #:integerpv
   #:interactive-stream-p
   #:intern
   #:internal-time-units-per-second
   #:intersection
   #:invalid-method-error
   #:invoke-debugger
   #:invoke-restart
   #:invoke-restart-interactively
   #:isqrt
   #:it
   #:ith-value
   #:kbo-builtin-constant-weight
   #:kbo-builtin-constant-weight?
   #:kbo-status
   #:kbo-status?
   #:kbo-variable-weight
   #:kbo-variable-weight?
   #:keyword
   #:keywordp
   #:known?
   #:labels
   #:lambda
   #:lambda-list-keywords
   #:lambda-parameters-limit
   #:last
   #:last-row
   #:lcm
   #:ldb
   #:ldb-test
   #:ldiff
   #:least-negative-double-float
   #:least-negative-long-float
   #:least-negative-normalized-double-float
   #:least-negative-normalized-long-float
   #:least-negative-normalized-short-float
   #:least-negative-normalized-single-float
   #:least-negative-short-float
   #:least-negative-single-float
   #:least-positive-double-float
   #:least-positive-long-float
   #:least-positive-normalized-double-float
   #:least-positive-normalized-long-float
   #:least-positive-normalized-short-float
   #:least-positive-normalized-single-float
   #:least-positive-short-float
   #:least-positive-single-float
   #:length
   #:let
   #:let*
   #:let-options
   #:level-pref-for-giving
   #:level-pref-for-giving?
   #:lifo
   #:linear-force
   #:lisp-implementation-type
   #:lisp-implementation-version
   #:list
   #:list*
   #:list-all-packages
   #:list-length
   #:listen
   #:listen-for-commands
   #:listen-for-commands?
   #:listp
   #:literal-ordering-a
   #:literal-ordering-n
   #:literal-ordering-p
   #:load
   #:load-logical-pathname-translations
   #:load-time-value
   #:local
   #:local-output
   #:locally
   #:log
   #:logand
   #:logandc1
   #:logandc2
   #:logbitp
   #:logcount
   #:logeqv
   #:logical-pathname
   #:logical-pathname-translations
   #:logior
   #:lognand
   #:lognor
   #:lognot
   #:logorc1
   #:logorc2
   #:logtest
   #:logxor
   #:long-float
   #:long-float-epsilon
   #:long-float-negative-epsilon
   #:long-site-name
   #:loop
   #:loop-finish
   #:lower-case-p
   #:machine-instance
   #:machine-type
   #:machine-version
   #:macro-function
   #:macroexpand
   #:macroexpand-1
   #:macrolet
   #:make-array
   #:make-broadcast-stream
   #:make-compound
   #:make-compound*
   #:make-concatenated-stream
   #:make-condition
   #:make-dispatch-macro-character
   #:make-echo-stream
   #:make-hash-table
   #:make-instance
   #:make-instances-obsolete
   #:make-list
   #:make-load-form
   #:make-load-form-saving-slots
   #:make-method
   #:make-package
   #:make-pathname
   #:make-random-state
   #:make-row-context
   #:make-sequence
   #:make-snark-system
   #:make-string
   #:make-string-input-stream
   #:make-string-output-stream
   #:make-symbol
   #:make-synonym-stream
   #:make-two-way-stream
   #:make-variable
   #:makunbound
   #:map
   #:map-into
   #:map-rows
   #:mapc
   #:mapcan
   #:mapcar
   #:mapcon
   #:maphash
   #:mapl
   #:maplist
   #:mark-as-given
   #:mask-field
   #:matches-compound
   #:matches-constant
   #:max
   #:maxv
   #:member
   #:member-if
   #:member-if-not
   #:memberv
   #:merge
   #:merge-pathnames
   #:meter-unify-bag
   #:meter-unify-bag?
   #:method
   #:method-combination
   #:method-combination-error
   #:method-qualifiers
   #:min
   #:minusp
   #:minv
   #:mismatch
   #:mod
   #:most-negative-double-float
   #:most-negative-fixnum
   #:most-negative-long-float
   #:most-negative-short-float
   #:most-negative-single-float
   #:most-positive-double-float
   #:most-positive-fixnum
   #:most-positive-long-float
   #:most-positive-short-float
   #:most-positive-single-float
   #:muffle-warning
   #:multiple-value-bind
   #:multiple-value-call
   #:multiple-value-call-nondeterministic
   #:multiple-value-list
   #:multiple-value-prog1
   #:multiple-value-setq
   #:multiple-values-limit
   #:my-source
   #:name-char
   #:name-row
   #:namestring
   #:natural
   #:nbutlast
   #:nconc
   #:necessarily?
   #:negated_conjecture
   #:negated_conjecture
   #:negated_question
   #:negative
   #:negative-hyperresolve
   #:negative-integer
   #:negative-number
   #:negative-rational
   #:negative-real
   #:new-prove
   #:new-row-context
   #:next-method-p
   #:nil
   #:nintersection
   #:ninth
   #:no-applicable-method
   #:no-next-method
   #:nondeterministic-function?
   #:nonnegative
   #:nonnegative-integer
   #:nonnegative-number
   #:nonnegative-rational
   #:nonnegative-real
   #:nonpositive
   #:nonzero
   #:nonzero-integer
   #:nonzero-number
   #:nonzero-rational
   #:nonzero-real
   #:not
   #:notany
   #:notevery
   #:notinline
   #:notv
   #:nreconc
   #:nreverse
   #:nset-difference
   #:nset-exclusive-or
   #:nstring-capitalize
   #:nstring-downcase
   #:nstring-upcase
   #:nsublis
   #:nsubst
   #:nsubst-if
   #:nsubst-if-not
   #:nsubstitute
   #:nsubstitute-if
   #:nsubstitute-if-not
   #:nth
   #:nth-value
   #:nthcdr
   #:null
   #:number
   #:number-of-given-rows-limit
   #:number-of-given-rows-limit?
   #:number-of-rows-limit
   #:number-of-rows-limit?
   #:numberp
   #:numberpv
   #:numerator
   #:nunion
   #:oddp
   #:one-value
   #:open
   #:open-stream-p
   #:optimize
   #:or
   #:ordering-functions>constants
   #:ordering-functions>constants?
   #:orv
   #:otherwise
   #:output-stream-p
   #:package
   #:package-error
   #:package-error-package
   #:package-name
   #:package-nicknames
   #:package-shadowing-symbols
   #:package-use-list
   #:package-used-by-list
   #:packagep
   #:pairlis
   #:paramodulate
   #:paramodulate-by
   #:parse-error
   #:parse-integer
   #:parse-namestring
   #:partition-communication-table
   #:partition-communication-table?
   #:pathname
   #:pathname-device
   #:pathname-directory
   #:pathname-host
   #:pathname-match-p
   #:pathname-name
   #:pathname-type
   #:pathname-version
   #:pathnamep
   #:peek-char
   #:phase
   #:pi
   #:plusp
   #:pop
   #:pop-row-context
   #:position
   #:position-if
   #:position-if-not
   #:positive
   #:positive-integer
   #:positive-number
   #:positive-rational
   #:positive-real
   #:possibly?
   #:pprint
   #:pprint-dispatch
   #:pprint-exit-if-list-exhausted
   #:pprint-fill
   #:pprint-indent
   #:pprint-linear
   #:pprint-logical-block
   #:pprint-newline
   #:pprint-pop
   #:pprint-tab
   #:pprint-tabular
   #:prin1
   #:prin1-to-string
   #:princ
   #:princ-to-string
   #:print
   #:print-agenda-when-finished
   #:print-agenda-when-finished?
   #:print-agendas
   #:print-ancestry
   #:print-assertion-analysis-notes
   #:print-assertion-analysis-notes?
   #:print-clocks-when-finished
   #:print-clocks-when-finished?
   #:print-feature-tree
   #:print-final-rows
   #:print-final-rows?
   #:print-given-row-lines-printing
   #:print-given-row-lines-printing?
   #:print-given-row-lines-signalling
   #:print-given-row-lines-signalling?
   #:print-irrelevant-rows
   #:print-irrelevant-rows?
   #:print-not-readable
   #:print-not-readable-object
   #:print-object
   #:print-options
   #:print-options-when-starting
   #:print-options-when-starting?
   #:print-pure-rows
   #:print-pure-rows?
   #:print-rewrite-orientation
   #:print-rewrite-orientation?
   #:print-rewrites
   #:print-row
   #:print-row-answers
   #:print-row-answers?
   #:print-row-constraints
   #:print-row-constraints?
   #:print-row-goals
   #:print-row-goals?
   #:print-row-length-limit
   #:print-row-length-limit?
   #:print-row-partitions
   #:print-row-partitions?
   #:print-row-reasons
   #:print-row-reasons?
   #:print-row-term
   #:print-row-wffs-prettily
   #:print-row-wffs-prettily?
   #:print-rows
   #:print-rows-prettily
   #:print-rows-prettily?
   #:print-rows-shortened
   #:print-rows-shortened?
   #:print-rows-test
   #:print-rows-test?
   #:print-rows-when-derived
   #:print-rows-when-derived?
   #:print-rows-when-finished
   #:print-rows-when-finished?
   #:print-rows-when-given
   #:print-rows-when-given?
   #:print-rows-when-processed
   #:print-rows-when-processed?
   #:print-sort-theory
   #:print-summary
   #:print-summary-when-finished
   #:print-summary-when-finished?
   #:print-symbol-ordering
   #:print-symbol-table
   #:print-symbol-table-warnings
   #:print-symbol-table-warnings?
   #:print-term
   #:print-term-memory-when-finished
   #:print-term-memory-when-finished?
   #:print-time-used
   #:print-time-used?
   #:print-unorientable-rows
   #:print-unorientable-rows?
   #:print-unreadable-object
   #:print-values
   #:probe-file
   #:proclaim
   #:profile
   #:prog
   #:prog*
   #:prog1
   #:prog2
   #:progn
   #:program-error
   #:progv
   #:proof
   #:proofs
   #:prove
   #:prove-closure
   #:prove-closure?
   #:prove-sequential
   #:prove-sequential?
   #:prove-supported
   #:prove-supported?
   #:provide
   #:pruning-tests
   #:pruning-tests-before-simplification
   #:pruning-tests-before-simplification?
   #:pruning-tests?
   #:psetf
   #:psetq
   #:purge
   #:purify
   #:push
   #:push-row-context
   #:pushnew
   #:question
   #:quote
   #:random
   #:random-state
   #:random-state-p
   #:range-size
   #:rassoc
   #:rassoc-if
   #:rassoc-if-not
   #:ratio
   #:rational
   #:rationalize
   #:rationalp
   #:rcc8-region-sort-name
   #:rcc8-region-sort-name?
   #:read
   #:read-assertion-file
   #:read-byte
   #:read-char
   #:read-char-no-hang
   #:read-delimited-list
   #:read-from-string
   #:read-infix-term
   #:read-line
   #:read-preserving-whitespace
   #:read-sequence
   #:reader-error
   #:readtable
   #:readtable-case
   #:readtablep
   #:real
   #:realp
   #:realpart
   #:realpv
   #:reduce
   #:refute-file
   #:refute-file-actions
   #:refute-file-actions?
   #:refute-file-closure
   #:refute-file-closure?
   #:refute-file-if-exists
   #:refute-file-if-exists?
   #:refute-file-ignore-errors
   #:refute-file-ignore-errors?
   #:refute-file-initialize
   #:refute-file-initialize?
   #:refute-file-options
   #:refute-file-options?
   #:refute-file-output-file
   #:refute-file-output-file?
   #:refute-file-verbose
   #:refute-file-verbose?
   #:region
   #:reinitialize-instance
   #:rem
   #:remf
   #:remhash
   #:remove
   #:remove-duplicates
   #:remove-if
   #:remove-if-not
   #:remove-method
   #:remprop
   #:rename-file
   #:rename-package
   #:reorder
   #:replace
   #:require
   #:resolve
   #:rest
   #:restart
   #:restart-bind
   #:restart-case
   #:restart-name
   #:restore-theory
   #:resume-snark
   #:return
   #:return-from
   #:revappend
   #:reverse
   #:rewrite
   #:rewrite-answers
   #:rewrite-answers?
   #:rewrite-constraints
   #:rewrite-constraints?
   #:room
   #:root-row-context
   #:rotatef
   #:round
   #:row
   #:row-ancestry
   #:row-answer
   #:row-argument-count-limit
   #:row-argument-count-limit?
   #:row-author
   #:row-constrained-p
   #:row-constraints
   #:row-depth
   #:row-documentation
   #:row-input-wff
   #:row-level
   #:row-major-aref
   #:row-name
   #:row-name-or-number
   #:row-neg-size+depth
   #:row-number
   #:row-parents
   #:row-reason
   #:row-rewrites-used
   #:row-size
   #:row-size+depth
   #:row-size+depth+level
   #:row-source
   #:row-weight
   #:row-weight+depth
   #:row-weight+depth+level
   #:row-weight-before-simplification-limit
   #:row-weight-before-simplification-limit-exceeded
   #:row-weight-before-simplification-limit?
   #:row-weight-limit
   #:row-weight-limit-exceeded
   #:row-weight-limit?
   #:row-wff
   #:row-wff&answer-weight+depth
   #:rows
   #:rplaca
   #:rplacd
   #:rpo-status
   #:rpo-status?
   #:run-time-limit
   #:run-time-limit?
   #:safety
   #:satisfies
   #:save-snark-system
   #:sbit
   #:scale-float
   #:schar
   #:search
   #:second
   #:sequence
   #:serious-condition
   #:set
   #:set-difference
   #:set-dispatch-macro-character
   #:set-exclusive-or
   #:set-macro-character
   #:set-options
   #:set-pprint-dispatch
   #:set-syntax-from-char
   #:setf
   #:setq
   #:seventh
   #:shadow
   #:shadowing-import
   #:shared-initialize
   #:shiftf
   #:short-float
   #:short-float-epsilon
   #:short-float-negative-epsilon
   #:short-site-name
   #:signal
   #:signed-byte
   #:signum
   #:simple-array
   #:simple-base-string
   #:simple-bit-vector
   #:simple-bit-vector-p
   #:simple-condition
   #:simple-condition-format-arguments
   #:simple-condition-format-control
   #:simple-error
   #:simple-string
   #:simple-string-p
   #:simple-type-error
   #:simple-vector
   #:simple-vector-p
   #:simple-warning
   #:sin
   #:single-float
   #:single-float-epsilon
   #:single-float-negative-epsilon
   #:sinh
   #:sixth
   #:sleep
   #:slot-boundp
   #:slot-exists-p
   #:slot-makunbound
   #:slot-missing
   #:slot-unbound
   #:slot-value
   #:software-type
   #:software-version
   #:solution
   #:some
   #:sort
   #:sort-author
   #:sort-disjoint?
   #:sort-documentation
   #:sort-intersection
   #:sort-name
   #:sort-name-p
   #:sort-source
   #:sortal
   #:space
   #:special
   #:special-operator-p
   #:speed
   #:sprofile
   #:sqrt
   #:stable-sort
   #:standard
   #:standard-char
   #:standard-char-p
   #:standard-class
   #:standard-generic-function
   #:standard-method
   #:standard-object
   #:static-ordering
   #:step
   #:storage-condition
   #:store-value
   #:stream
   #:stream-element-type
   #:stream-error
   #:stream-error-stream
   #:stream-external-format
   #:streamp
   #:string
   #:string-capitalize
   #:string-downcase
   #:string-equal
   #:string-greaterp
   #:string-left-trim
   #:string-lessp
   #:string-not-equal
   #:string-not-greaterp
   #:string-not-lessp
   #:string-right-trim
   #:string-stream
   #:string-trim
   #:string-upcase
   #:string/=
   #:string<
   #:string<=
   #:string=
   #:string>
   #:string>=
   #:stringp
   #:structure
   #:structure-class
   #:structure-object
   #:style-warning
   #:sublis
   #:subseq
   #:subsetp
   #:subsort?
   #:subst
   #:subst-if
   #:subst-if-not
   #:substitute
   #:substitute-if
   #:substitute-if-not
   #:subtypep
   #:suspend-and-resume-snark
   #:suspend-snark
   #:svref
   #:sxhash
   #:symbol
   #:symbol-function
   #:symbol-macrolet
   #:symbol-name
   #:symbol-package
   #:symbol-plist
   #:symbol-table-constant?
   #:symbol-table-entries
   #:symbol-table-function?
   #:symbol-table-relation?
   #:symbol-value
   #:symbolp
   #:synonym-stream
   #:synonym-stream-symbol
   #:t
   #:tagbody
   #:tailp
   #:tan
   #:tanh
   #:tell
   #:template
   #:temporal
   #:tenth
   #:term-sort
   #:term-to-lisp
   #:terpri
   #:tff
   #:the
   #:the-bag
   #:the-complex
   #:the-integer
   #:the-list
   #:the-natural
   #:the-negative
   #:the-nonnegative
   #:the-nonnegative-integer
   #:the-nonpositive
   #:the-nonzero
   #:the-number
   #:the-positive
   #:the-positive-integer
   #:the-rational
   #:the-real
   #:the-sort
   #:the-string
   #:the-zero
   #:third
   #:throw
   #:time
   #:time-interval
   #:time-interval-sort-name
   #:time-interval-sort-name?
   #:time-point
   #:time-point-sort-name
   #:time-point-sort-name?
   #:top-sort
   #:top-sort-a
   #:tptp-nonnumber
   #:trace
   #:trace-dp-refute
   #:trace-dp-refute?
   #:trace-dpll-subsumption
   #:trace-dpll-subsumption?
   #:trace-optimize-sparse-vector-expression
   #:trace-optimize-sparse-vector-expression?
   #:trace-rewrite
   #:trace-rewrite?
   #:trace-unify
   #:trace-unify-bag-basis
   #:trace-unify-bag-basis?
   #:trace-unify-bag-bindings
   #:trace-unify-bag-bindings?
   #:trace-unify?
   #:trail
   #:translate-logical-pathname
   #:translate-pathname
   #:tree-equal
   #:truename
   #:truncate
   #:two-way-stream
   #:two-way-stream-input-stream
   #:two-way-stream-output-stream
   #:type
   #:type
   #:type-error
   #:type-error-datum
   #:type-error-expected-type
   #:type-of
   #:typecase
   #:typep
   #:unbound-slot
   #:unbound-slot-instance
   #:unbound-variable
   #:uncheckpoint-theory
   #:undefined
   #:undefined-function
   #:unexport
   #:unify
   #:unify-bag-basis-size-limit
   #:unify-bag-basis-size-limit?
   #:unintern
   #:union
   #:unless
   #:unread-char
   #:unsigned-byte
   #:untrace
   #:unuse-package
   #:unwedge-screamer
   #:unwind-protect
   #:unwind-trail
   #:update-instance-for-different-class
   #:update-instance-for-redefined-class
   #:upgraded-array-element-type
   #:upgraded-complex-part-type
   #:upper-case-p
   #:ur-resolve
   #:use-ac-connectives
   #:use-ac-connectives?
   #:use-answers-during-subsumption
   #:use-answers-during-subsumption?
   #:use-assertion-analysis
   #:use-assertion-analysis?
   #:use-associative-identity
   #:use-associative-identity?
   #:use-associative-unification
   #:use-associative-unification?
   #:use-clausification
   #:use-clausification?
   #:use-closure-when-satisfiable
   #:use-closure-when-satisfiable?
   #:use-condensing
   #:use-condensing?
   #:use-conditional-answer-creation
   #:use-conditional-answer-creation?
   #:use-constraint-purification
   #:use-constraint-purification?
   #:use-constraint-solver-in-subsumption
   #:use-constraint-solver-in-subsumption?
   #:use-constructive-answer-restriction
   #:use-constructive-answer-restriction?
   #:use-default-ordering
   #:use-default-ordering?
   #:use-dp-subsumption
   #:use-dp-subsumption?
   #:use-embedded-rewrites
   #:use-embedded-rewrites?
   #:use-equality-elimination
   #:use-equality-elimination?
   #:use-equality-factoring
   #:use-equality-factoring?
   #:use-extended-implications
   #:use-extended-implications?
   #:use-extended-quantifiers
   #:use-extended-quantifiers?
   #:use-factoring
   #:use-factoring?
   #:use-function-creation
   #:use-function-creation?
   #:use-hyperresolution
   #:use-hyperresolution?
   #:use-indefinite-answers
   #:use-indefinite-answers?
   #:use-input-restriction
   #:use-input-restriction?
   #:use-literal-ordering-with-hyperresolution
   #:use-literal-ordering-with-hyperresolution?
   #:use-literal-ordering-with-negative-hyperresolution
   #:use-literal-ordering-with-negative-hyperresolution?
   #:use-literal-ordering-with-paramodulation
   #:use-literal-ordering-with-paramodulation?
   #:use-literal-ordering-with-resolution
   #:use-literal-ordering-with-resolution?
   #:use-literal-ordering-with-ur-resolution
   #:use-literal-ordering-with-ur-resolution?
   #:use-lookahead-in-dpll-for-subsumption
   #:use-lookahead-in-dpll-for-subsumption?
   #:use-magic-transformation
   #:use-magic-transformation?
   #:use-negative-hyperresolution
   #:use-negative-hyperresolution?
   #:use-package
   #:use-paramodulation
   #:use-paramodulation-only-from-units
   #:use-paramodulation-only-from-units?
   #:use-paramodulation-only-into-units
   #:use-paramodulation-only-into-units?
   #:use-paramodulation?
   #:use-partitions
   #:use-partitions?
   #:use-purity-test
   #:use-purity-test?
   #:use-quantifier-preservation
   #:use-quantifier-preservation?
   #:use-relevance-test
   #:use-relevance-test?
   #:use-replacement-resolution-with-x=x
   #:use-replacement-resolution-with-x=x?
   #:use-resolution
   #:use-resolution?
   #:use-resolve-code
   #:use-resolve-code?
   #:use-simplification-by-equalities
   #:use-simplification-by-equalities?
   #:use-simplification-by-units
   #:use-simplification-by-units?
   #:use-single-replacement-paramodulation
   #:use-single-replacement-paramodulation?
   #:use-sort-relativization
   #:use-sort-relativization?
   #:use-subsume-bag
   #:use-subsume-bag?
   #:use-subsumption
   #:use-subsumption-by-false
   #:use-subsumption-by-false?
   #:use-subsumption?
   #:use-term-memory-deletion
   #:use-term-memory-deletion?
   #:use-term-ordering
   #:use-term-ordering-cache
   #:use-term-ordering-cache?
   #:use-term-ordering?
   #:use-to-lisp-code
   #:use-to-lisp-code?
   #:use-unit-restriction
   #:use-unit-restriction?
   #:use-ur-pttp
   #:use-ur-pttp?
   #:use-ur-resolution
   #:use-ur-resolution?
   #:use-value
   #:use-variable-name-sorts
   #:use-variable-name-sorts?
   #:use-well-sorting
   #:use-well-sorting?
   #:user-homedir-pathname
   #:value-of
   #:values
   #:values-list
   #:var
   #:variable
   #:variable-p
   #:variable-sort
   #:variable-sort-marker
   #:variable-sort-marker?
   #:variable-symbol-prefixes
   #:variable-symbol-prefixes?
   #:variable-to-lisp-code
   #:variable-to-lisp-code?
   #:variable-weight
   #:variable-weight?
   #:vector
   #:vector-pop
   #:vector-push
   #:vector-push-extend
   #:vectorp
   #:warn
   #:warning
   #:when
   #:when-failing
   #:when-system
   #:wild-pathname-p
   #:with-accessors
   #:with-compilation-unit
   #:with-condition-restarts
   #:with-hash-table-iterator
   #:with-input-from-string
   #:with-no-output
   #:with-open-file
   #:with-open-stream
   #:with-output-to-string
   #:with-package-iterator
   #:with-simple-restart
   #:with-slots
   #:with-standard-io-syntax
   #:write
   #:write-byte
   #:write-char
   #:write-line
   #:write-sequence
   #:write-string
   #:write-to-string
   #:y-or-n-p
   #:yes-or-no-p
   #:zero
   #:zerop))

(defpackage #:poem-user
  (:use #:common-lisp-user #:poem))
